# Generated by Django 6.0.1 on 2026-01-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rice', 'Rice'), ('pulses', 'Pulses'), ('oils', 'Oils'), ('spices', 'Spices'), ('dryfruits', 'Dry Fruits'), ('others', 'Other Groceries')], max_length=50),
        ),
    ]
